version: '3.8'

services:
  # 开发环境
  blog-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --host 0.0.0.0
    profiles:
      - dev

  # 生产环境
  blog-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod

  # 预览环境（构建后预览）
  blog-preview:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "4321:4321"
    command: pnpm preview --host 0.0.0.0
    profiles:
      - preview 