version: '3.8'

services:
  blog-dev:
    # 开发环境的自定义配置
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.astro
    environment:
      - NODE_ENV=development
      - ASTRO_TELEMETRY_DISABLED=1
    # 启用热重载
    command: pnpm dev --host 0.0.0.0 --port 4321 